apiVersion: networking.gke.io/v1alpha1
kind: NetworkLogging
metadata:
  name: default
spec:
  cluster:
    deny:
      log: true
      delegate: false
    allow:
      log: false
      delegate: false
